name: 03-workflow-runner

on: workflow_dispatch

jobs:
    ubuntu-echo:
        runs-on: ubuntu-latest
        steps:
          - name: Show os
            run: |
               echo "This Jobs is running on an ubuntu server"
               echo "Runner OS: $RUNNER_OS"
    windows-echo:
        runs-on: windows-latest
        steps:
          - name: Show os
            shell: bash
            run: |
               echo "This is running on a windows runner"
               echo "RUNNER_OS: $RUNNER_OS"
